### ISSUE TITLE
Add live demo

### ISSUE THREAD

**Issue by dhvcc** [nomilkinmyhome/todo-list#1]
I would suggest you deploying the app to heroku or azure to have a nice live demo showcasing the look and functionality

Keep in mind to limit database writes to 10000 or your app can crash after reaching db limit (heroku)

**Comment by nomilkinmyhome** [comment]
Hi. Thank you for your suggestion. 
Yes, I plan to deploy, but at the moment there is nothing to show, so it will be a little later.

**Comment by nomilkinmyhome** [comment]
Done: https://nomilkinmyhome-todolistapp.herokuapp.com/
